### ISSUE TITLE
Top margin in popout window

### ISSUE THREAD

**Issue by kristianserrano** [mclemente/fvtt-dice-tray#21]
I'd like to try to help with the top margin issue you mentioned in the release, but I don't see the "orange numbers" to which you were referring.

**Comment by mclemente** [comment]
Hey, thank you for the help! I mean the numbers that show up when you select a dice (see images 1 and 2).
![image](https://github.com/user-attachments/assets/dbb3fe1b-8ca3-45b3-99ef-405b72b89788)


![image](https://github.com/user-attachments/assets/0815574d-a522-4e40-ae03-26c01500c4e9)

The issue is that I couldn't get them to overflow from the popout like they do on the chat sidebar. This is how it looks with 0 margin on `#dice-tray-popout .dice-tray`.
![image](https://github.com/user-attachments/assets/a3757cb4-c199-4d33-9091-38c8b14c3b7c)

**Comment by kristianserrano** [comment]
Yeah, I can take a look at that.

**Comment by kristianserrano** [comment]
MR submitted!
